steps:
    # build the container image using doccker
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}",
        "."
      ]

  # push built image to the container registry
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"
      ]

  # start the image in cloud run
  # https://cloud.google.com/sdk/gcloud/reference/run/deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--timeout",
        "900",
        "--update-env-vars",
        "ENVIRONMENT=${_ENVIRONMENT}"
      ]
